version: 0.0
os: linux
files:
   - source: /
     destination: /home/ec2-user/django/django-app
file_exists_behavior: OVERWRITE     

hooks:
  BeforeInstall:
   - location: scripts/before_install.sh
  AfterInstall:
   - location: scripts/after_install.sh
     timeout: 180
