version: 0.2

phases:
  install:
    commands:
      - pip install -r requirements.txt
            
  pre_build:
    commands:
      - python manage.py django-test
  
artifacts:
  files:
    - "**/*"
  discard-paths: no
